cuzchu
lillix1qq
Visual Studio Code


sooooooq — 2025/06/12 16:58
#@author
#@category Function
#@keybinding
#@menupath
#@toolbar

"""
Renames or creates functions in a Ghidra program using a CSV file.
CSV format: address,size,name
"""

import csv
import os

from ghidra.program.model.symbol import SourceType
from ghidra.program.model.listing import Function
from ghidra.program.model.listing import FunctionManager
from ghidra.program.model.address import Address

# === CONFIGURATION ===
# フルパス or 相対パスでCSVファイルを指定
CSV_PATH = "/absolute/path/to/functions.csv"

# === FUNCTIONS ===

def get_address(addr_str):
    """Convert hex string to Ghidra Address object."""
    addr_factory = currentProgram.getAddressFactory()
    return addr_factory.getAddress(addr_str)

def can_overwrite_name(name):
    """Filter out autogenerated or junk names."""
    return not name.startswith(("FUN_", "nullsub_", "j_")) and name != ""

def rename_or_create_functions():
    fm = currentProgram.getFunctionManager()
    listing = currentProgram.getListing()

    with open(CSV_PATH, "r") as f:
        reader = csv.reader(f)
        next(reader)  # skip header

        count = 0

        for row in reader:
            addr_str = row[0]
            size = int(row[2])
            name = row[3]

            addr = get_address(addr_str)
            func = fm.getFunctionAt(addr)

            if func is None:
                # Create function if it doesn't exist
                print(f"Creating function at {addr} with name {name}")
                try:
                    func = createFunction(addr, None)
                except Exception as e:
                    print(f"Failed to create function at {addr}: {e}")
                    continue

            # Set function body size if needed
            if func.getBody().getMinAddress() != addr:
                print(f"Fixing function start at {addr}")
                try:
                    func = createFunction(addr, None)
                except Exception as e:
                    print(f"Failed to fix function at {addr}: {e}")
                    continue

            # Rename function
            if can_overwrite_name(name):
                try:
                    func.setName(name, SourceType.USER_DEFINED)
                    count += 1
                except Exception as e:
                    print(f"Failed to rename function at {addr}: {e}")
        print(f"Renaming completed. Total renamed: {count}")

# === EXECUTE ===
rename_or_create_functions()

rename_functions_in_ghidra.py
3 KB
一応動くと思うけど試して
下痢

 — 2025/06/12 18:31
ナイスあとで試すわ
﻿
#@author
#@category Function
#@keybinding
#@menupath
#@toolbar

"""
Renames or creates functions in a Ghidra program using a CSV file.
CSV format: address,size,name
"""

import csv
import os

from ghidra.program.model.symbol import SourceType
from ghidra.program.model.listing import Function
from ghidra.program.model.listing import FunctionManager
from ghidra.program.model.address import Address

# === CONFIGURATION ===
# フルパス or 相対パスでCSVファイルを指定
CSV_PATH = "/absolute/path/to/functions.csv"

# === FUNCTIONS ===

def get_address(addr_str):
    """Convert hex string to Ghidra Address object."""
    addr_factory = currentProgram.getAddressFactory()
    return addr_factory.getAddress(addr_str)

def can_overwrite_name(name):
    """Filter out autogenerated or junk names."""
    return not name.startswith(("FUN_", "nullsub_", "j_")) and name != ""

def rename_or_create_functions():
    fm = currentProgram.getFunctionManager()
    listing = currentProgram.getListing()

    with open(CSV_PATH, "r") as f:
        reader = csv.reader(f)
        next(reader)  # skip header

        count = 0

        for row in reader:
            addr_str = row[0]
            size = int(row[2])
            name = row[3]

            addr = get_address(addr_str)
            func = fm.getFunctionAt(addr)

            if func is None:
                # Create function if it doesn't exist
                print(f"Creating function at {addr} with name {name}")
                try:
                    func = createFunction(addr, None)
                except Exception as e:
                    print(f"Failed to create function at {addr}: {e}")
                    continue

            # Set function body size if needed
            if func.getBody().getMinAddress() != addr:
                print(f"Fixing function start at {addr}")
                try:
                    func = createFunction(addr, None)
                except Exception as e:
                    print(f"Failed to fix function at {addr}: {e}")
                    continue

            # Rename function
            if can_overwrite_name(name):
                try:
                    func.setName(name, SourceType.USER_DEFINED)
                    count += 1
                except Exception as e:
                    print(f"Failed to rename function at {addr}: {e}")
        print(f"Renaming completed. Total renamed: {count}")

# === EXECUTE ===
rename_or_create_functions()
rename_functions_in_ghidra.py

