cuzchu
lillix1qq
Visual Studio Code

ここがプライベートチャンネル「#・general仮」の始まりです。
下痢

 — 2025/06/08 21:03
カスタムスカイにて高画質でプレイしたい場合はsky.pngの画像サイズを4032×2688にすると綺麗になります。
@white. 一応豆知識的なことを
white. — 2025/06/08 21:20
りょ
下痢

 — 2025/06/08 21:56
プレイヤーが赤くなる
[Hottest Person?????]
580F0000 017C57B8 
580F1000 00000150 
780F0000 000000D0
640F0000 00000000 01010001
[擬似連打オートクリッカー]
580F0000 017C57B8
580F1000 00000150
580F1000 00000228
780F0000 000000FF
640F0000 00000000 3FA9999A

80000200
58050000 017DB628
78050000 00000024
98965000
58061000 00000000
74061000 00400000
A8650000
[ Hitbox Recolor]
80002000 
040F0000 0068AF08 D503201F 
04000000 0068AF40 32005FE2 
04000000 0068B114 32001FE1 
04000000 0068B0DC 32101FE1 
20000000 
80004000 
040F0000 0068AF08 D503201F 
04000000 0068AF40 32181FE2 
04000000 0068B114 32181FE1 
04000000 0068B0DC 32181FE1 
20000000 
80001000 
040F0000 0068AF08 D503201F 
04000000 0068AF40 32009FE2 
04000000 0068B114 32009FE1 
04000000 0068B0DC 32009FE1 
20000000 
80008000 
040F0000 0068AF08 D503201F 
04000000 0068AF40 320503E2 
04000000 0068B114 32183FE1 
04000000 0068B0DC 32183FE1 
20000000 
マントがバグるコード
 ^視野変更作る時にたまたま見つけたコード
[Bug cape]
580F0000 017C57B8
580F1000 00000150
580F1000 00000228
780F0000 0000042F
640F0000 00000000 01000101
下痢

 — 2025/06/09 1:43
[itemPhysics]
04000000 006B1100 1E229000 
04000000 006B1108 D503201F 
04000000 006B1208 1E2E1000 
04000000 006B3498 1E2E1001 
04000000 006B34BC 17F52760 
08000000 006B34C0 1E2703E2 1E2E1001 
04000000 006B34C8 1E2703E3 
08000000 003FD234 D65F03C0 52800020 
08000000 003FD23C F94002E8 1E200820 
08000000 003FD244 35000040 39430100 
08000000 003FD24C 52800B40 140AD89D 
08000000 003FD254 1E2E1001 1E220000 
08000000 003FD25C 1E2703E3 1E2703E2 
08000000 003FD264 140AD89A 940A14A4
アイテムをドロップした時にリアルになる
下痢

 — 2025/06/10 15:02
ZL=80000100
ZR=80000200
L=80000040
R=80000080
A=80000001
B=80000002
X=80000004
Y=80000008
↑=80002000
↓=80008000
←=80001000
→=80004000
L3=80000010
R3=80000020
LR=800000C0
ZLZR=80000300
ボタンコード
[block hitline]
08000000 006A4680 1E2E1003 1E2E1000
04000000 006A476C 12BFE001 
下痢

 — 2025/06/10 15:14
食べるスピードが早くなる。
十字キー↑適応↓解除
[Fast eat by kainn]
80002000 
040F0000 00220C68 D503201F 
20000000 
80008000 
040F0000 00220C68 35000168 
20000000
自鯖限定
[HostOption in MG]
04000000 005C9564 D503201F
自分以外の↑とても不安定ロビー内だけ自由だが、始まるとエラー吐く
white. — 2025/06/11 1:14
これ？
下痢

 — 2025/06/11 1:15
いえっざ
ー
下痢

 — 2025/06/12 13:53
@sooooooq 関数名置き換えるスクリプト作ってくれ。
なんかidaライセンス消えたからギドラ用でおねが、
sooooooq — 2025/06/12 16:58
#@author
#@category Function
#@keybinding
#@menupath
#@toolbar

"""
Renames or creates functions in a Ghidra program using a CSV file.
CSV format: address,size,name
"""

import csv
import os

from ghidra.program.model.symbol import SourceType
from ghidra.program.model.listing import Function
from ghidra.program.model.listing import FunctionManager
from ghidra.program.model.address import Address

# === CONFIGURATION ===
# フルパス or 相対パスでCSVファイルを指定
CSV_PATH = "/absolute/path/to/functions.csv"

# === FUNCTIONS ===

def get_address(addr_str):
    """Convert hex string to Ghidra Address object."""
    addr_factory = currentProgram.getAddressFactory()
    return addr_factory.getAddress(addr_str)

def can_overwrite_name(name):
    """Filter out autogenerated or junk names."""
    return not name.startswith(("FUN_", "nullsub_", "j_")) and name != ""

def rename_or_create_functions():
    fm = currentProgram.getFunctionManager()
    listing = currentProgram.getListing()

    with open(CSV_PATH, "r") as f:
        reader = csv.reader(f)
        next(reader)  # skip header

        count = 0

        for row in reader:
            addr_str = row[0]
            size = int(row[2])
            name = row[3]

            addr = get_address(addr_str)
            func = fm.getFunctionAt(addr)

            if func is None:
                # Create function if it doesn't exist
                print(f"Creating function at {addr} with name {name}")
                try:
                    func = createFunction(addr, None)
                except Exception as e:
                    print(f"Failed to create function at {addr}: {e}")
                    continue

            # Set function body size if needed
            if func.getBody().getMinAddress() != addr:
                print(f"Fixing function start at {addr}")
                try:
                    func = createFunction(addr, None)
                except Exception as e:
                    print(f"Failed to fix function at {addr}: {e}")
                    continue

            # Rename function
            if can_overwrite_name(name):
                try:
                    func.setName(name, SourceType.USER_DEFINED)
                    count += 1
                except Exception as e:
                    print(f"Failed to rename function at {addr}: {e}")
        print(f"Renaming completed. Total renamed: {count}")

# === EXECUTE ===
rename_or_create_functions()

rename_functions_in_ghidra.py
3 KB
一応動くと思うけど試して
下痢

 — 2025/06/12 18:31
ナイスあとで試すわ
﻿
#@author
#@category Function
#@keybinding
#@menupath
#@toolbar

"""
Renames or creates functions in a Ghidra program using a CSV file.
CSV format: address,size,name
"""

import csv
import os

from ghidra.program.model.symbol import SourceType
from ghidra.program.model.listing import Function
from ghidra.program.model.listing import FunctionManager
from ghidra.program.model.address import Address

# === CONFIGURATION ===
# フルパス or 相対パスでCSVファイルを指定
CSV_PATH = "/absolute/path/to/functions.csv"

# === FUNCTIONS ===

def get_address(addr_str):
    """Convert hex string to Ghidra Address object."""
    addr_factory = currentProgram.getAddressFactory()
    return addr_factory.getAddress(addr_str)

def can_overwrite_name(name):
    """Filter out autogenerated or junk names."""
    return not name.startswith(("FUN_", "nullsub_", "j_")) and name != ""

def rename_or_create_functions():
    fm = currentProgram.getFunctionManager()
    listing = currentProgram.getListing()

    with open(CSV_PATH, "r") as f:
        reader = csv.reader(f)
        next(reader)  # skip header

        count = 0

        for row in reader:
            addr_str = row[0]
            size = int(row[2])
            name = row[3]

            addr = get_address(addr_str)
            func = fm.getFunctionAt(addr)

            if func is None:
                # Create function if it doesn't exist
                print(f"Creating function at {addr} with name {name}")
                try:
                    func = createFunction(addr, None)
                except Exception as e:
                    print(f"Failed to create function at {addr}: {e}")
                    continue

            # Set function body size if needed
            if func.getBody().getMinAddress() != addr:
                print(f"Fixing function start at {addr}")
                try:
                    func = createFunction(addr, None)
                except Exception as e:
                    print(f"Failed to fix function at {addr}: {e}")
                    continue

            # Rename function
            if can_overwrite_name(name):
                try:
                    func.setName(name, SourceType.USER_DEFINED)
                    count += 1
                except Exception as e:
                    print(f"Failed to rename function at {addr}: {e}")
        print(f"Renaming completed. Total renamed: {count}")

# === EXECUTE ===
rename_or_create_functions()
rename_functions_in_ghidra.py
3 KB
